# Generated by Django 3.2.7 on 2021-11-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='data',
            field=models.DateField(),
        ),
    ]
